# Generated by Django 2.2.5 on 2019-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191123_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_no',
            field=models.IntegerField(unique=True),
        ),
    ]
