# Generated by Django 2.2.5 on 2019-11-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191124_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='products.item'),
        ),
    ]
